"""
Django settings for cms_webapp project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/

For more information and full documentation (the latest stable version) DjangoCMS, see
https://docs.django-cms.org/en/latest/
"""
import os
from pathlib import Path

# import cms.middleware.toolbar

from config import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [

    # Optional but strongly recommended component for DjangoCMS; provides some styling to make CMS administration
    # components easier to work with.
    # It needs to be placed BEFORE django.contrib.admin.
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # DjangoCMS needs to use Django's django.contrib.sites framework.SITE_ID in the settings needs to be set up.
    # SITE_ID = 1 will suffice.
    'django.contrib.sites',

    # cms and menus are core DjangoCMS modules.
    'cms',
    'menus',

    # django-treebeard is used to manage DjangoCMS's page and plugin tree.
    'treebeard',

    # django-sekizai is required for static files management for DjangoCMS
    # It requires additional setting in TEMPLATES|context_processors
    'sekizai',

]

# SITE_ID for django.contrib.sites framework - see INSTALLED_APPS
SITE_ID = 1

MIDDLEWARE = [

    # ApphookReloadMiddleware useful for DjangoCMS
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # middleware required by DjangoCMS:

    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
]

# for DjangoCMS
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'cms_webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # required by DjangoCMS
                'cms.context_processors.cms_settings',

                # django_sekizai setting required for DjangoCMS
                'sekizai.context_processors.sekizai',

                # required by DjangoCMS internationalization
                'django.template.context_processors.i18n'
            ],
        },
    },
]

# DjangoCMS requires at least one template for its pages; they are defined here.
# The first template on the list is a default template for the project.
CMS_TEMPLATES = [
    ('base.html', 'Home page template'),
]

WSGI_APPLICATION = 'cms_webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    # }
    'default': {
        # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # Add DB name or path to db file if using sqlite3.
        'NAME': config.POSTGRES_DB,
        'USER': config.POSTGRES_USER,
        'PASSWORD': config.POSTGRES_PASSWORD,
        'HOST': config.POSTGRES_HOST,
        'PORT': config.POSTGRES_PORT,
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# Set up the languages of the project you want to use here (LANGUAGE_CODE setting is required by DjangoCMS).
LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('de', 'German'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Static files root needs to be updated for production!
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = 'static/'

# Media files uploaded by the user.
# Media files root needs to be updated for production!
# https://docs.djangoproject.com/en/4.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
